import type { ComponenteBus } from "@/lib/datos/tipos";
import { CITAS_EQUIPO_CARRETERA } from "@/lib/datos/normativa-inspeccion";

/**
 * Catálogo de los 23 componentes de la Inspección Diaria. Es contenido
 * estático: no vive en Supabase (ver supabase/migrations/0003_inspecciones.sql,
 * sección "componente_id sin FK") para que editar una ficha no requiera
 * una migración. `inspeccion_items.componente_id` se valida con zod contra
 * los ids de este archivo en el borde de cada Server Action.
 *
 * Sustento legal estricto: solo "equipo-carretera" cita textualmente la
 * Ley 769/2002 Art. 30 y la Res. 40595/2022 (PESV), tal como se pidió. El
 * resto usa `buenaPractica` con criterio estándar de mantenimiento
 * automotor, nunca una norma inventada.
 */
export const componentes: ComponenteBus[] = [
  {
    id: "motor",
    nombre: "Motor",
    icono: "motor",
    criticidad: "amarillo",
    descripcion:
      "Unidad que convierte combustible en energía mecánica para mover el bus.",
    funcion:
      "Provee la potencia de tracción y acciona los sistemas auxiliares (alternador, compresor de aire, dirección hidráulica).",
    importancia:
      "Una falla en marcha inmoviliza el bus con pasajeros a bordo y puede derivar en varada en vía o incendio.",
    pasosInspeccion: [
      "Con el motor apagado y frío, abrir el capó y revisar fugas visibles de aceite o líquidos en el piso bajo el bus.",
      "Arrancar y escuchar 30 segundos: ruidos metálicos, cascabeleo o vibración anormal.",
      "Observar el color del humo de escape al acelerar en vacío (blanco, azul o negro sostenido son anómalos).",
      "Verificar que no se enciendan testigos de falla en el tablero tras el arranque.",
    ],
    senalesDesgaste: [
      "Humo azul (quema aceite) o blanco denso sostenido (posible junta de culata).",
      "Pérdida de potencia en pendientes que antes subía sin esfuerzo.",
      "Vibración nueva en ralentí.",
    ],
    fallasComunes: [
      "Fuga de aceite por retenedores o cárter.",
      "Correas flojas o agrietadas.",
      "Filtro de combustible obstruido.",
    ],
    riesgos: [
      "Varada en vía con pasajeros a bordo.",
      "Incendio por fuga de combustible o aceite sobre partes calientes.",
      "Daño mayor al motor por seguir operando con una falla menor no atendida.",
    ],
    mantenimientoPreventivo: [
      "Cambio de aceite y filtro según el plan de mantenimiento del fabricante.",
      "Revisión de correas y mangueras en cada mantenimiento programado.",
      "Escaneo de códigos de falla cuando se encienda un testigo.",
    ],
    frecuencia: "Inspección visual diaria (preoperacional).",
    citasLegales: null,
    buenaPractica:
      "Buena práctica estándar de mantenimiento automotor: inspección visual preoperacional de fugas, ruidos y humo antes de cada salida.",
    tiposNovedad: [
      "Fuga de aceite o líquidos",
      "Ruido anormal",
      "Humo excesivo",
      "Pérdida de potencia",
      "Testigo de falla encendido",
    ],
    enChequeoRapido: false,
  },
  {
    id: "aceite",
    nombre: "Nivel de aceite",
    icono: "aceite",
    criticidad: "amarillo",
    descripcion: "Lubricante que reduce la fricción y el desgaste entre las piezas móviles del motor.",
    funcion: "Lubrica, enfría y limpia internamente el motor, prolongando la vida de sus componentes.",
    importancia:
      "Un nivel bajo o un aceite degradado puede fundir el motor en pocos minutos de operación.",
    pasosInspeccion: [
      "Con el bus en superficie plana y motor frío (o apagado ≥5 min), retirar la varilla y limpiarla.",
      "Insertar y retirar de nuevo: el nivel debe quedar entre las marcas mínima y máxima.",
      "Observar el color y la textura: debe ser ámbar u oscuro translúcido, nunca lechoso ni con partículas.",
    ],
    senalesDesgaste: [
      "Nivel por debajo de la marca mínima.",
      "Aceite lechoso (posible entrada de refrigerante).",
      "Olor a quemado o consistencia muy espesa.",
    ],
    fallasComunes: ["Consumo excesivo por desgaste de anillos.", "Fuga por el tapón de drenaje o el filtro."],
    riesgos: ["Agarrotamiento del motor.", "Pérdida total de potencia en plena vía."],
    mantenimientoPreventivo: [
      "Completar nivel con el aceite de la especificación del fabricante, nunca mezclar tipos.",
      "Cambio de aceite y filtro en el intervalo de kilometraje indicado.",
    ],
    frecuencia: "Verificación diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Verificación diaria de nivel y estado, práctica estándar previa a cualquier salida.",
    tiposNovedad: ["Nivel bajo", "Aceite contaminado", "Fuga visible"],
    enChequeoRapido: false,
  },
  {
    id: "refrigerante",
    nombre: "Refrigerante",
    icono: "refrigerante",
    criticidad: "amarillo",
    descripcion: "Líquido que circula por el motor absorbiendo y disipando el calor generado.",
    funcion: "Mantiene la temperatura del motor dentro del rango seguro de operación.",
    importancia: "Sin nivel adecuado el motor se sobrecalienta y puede sufrir daños irreversibles en minutos.",
    pasosInspeccion: [
      "Con el motor frío, revisar el nivel en el depósito de expansión (nunca abrir el radiador en caliente).",
      "Verificar que el nivel esté entre las marcas MIN y MAX.",
      "Inspeccionar mangueras y radiador en busca de fugas o manchas de refrigerante seco.",
    ],
    senalesDesgaste: ["Nivel bajo recurrente (indica fuga).", "Color turbio o con óxido.", "Manchas verdes o rosadas bajo el bus."],
    fallasComunes: ["Fuga por manguera agrietada o abrazadera floja.", "Tapón de radiador que no sella."],
    riesgos: ["Sobrecalentamiento del motor.", "Varada por daño de junta de culata."],
    mantenimientoPreventivo: ["Completar solo con el refrigerante especificado por el fabricante.", "Revisar mangueras y sello del radiador en cada mantenimiento."],
    frecuencia: "Verificación diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Verificación diaria de nivel en frío, práctica estándar de mantenimiento preventivo.",
    tiposNovedad: ["Nivel bajo", "Fuga visible", "Color anormal"],
    enChequeoRapido: false,
  },
  {
    id: "filtro-aire",
    nombre: "Filtro de aire",
    icono: "filtro-aire",
    criticidad: "verde",
    descripcion: "Elemento filtrante que limpia el aire antes de que entre a la cámara de combustión.",
    funcion: "Evita que polvo y partículas dañen los componentes internos del motor.",
    importancia: "Un filtro obstruido reduce potencia y aumenta el consumo de combustible.",
    pasosInspeccion: [
      "Abrir la carcasa del filtro y retirarlo.",
      "Verificar visualmente el nivel de suciedad a contraluz.",
      "Revisar que la carcasa y las mangueras de admisión no tengan grietas.",
    ],
    senalesDesgaste: ["Elemento oscurecido u obstruido.", "Pérdida de potencia o mayor consumo de combustible."],
    fallasComunes: ["Saturación por polvo en rutas destapadas.", "Fisuras en la carcasa que permiten entrada de aire sin filtrar."],
    riesgos: ["Desgaste acelerado del motor por ingreso de partículas."],
    mantenimientoPreventivo: ["Limpieza o reemplazo según el intervalo del fabricante o antes si la ruta es muy polvorienta."],
    frecuencia: "Revisión semanal o según intervalo del fabricante.",
    citasLegales: null,
    buenaPractica: "Inspección periódica estándar del sistema de admisión de aire.",
    tiposNovedad: ["Filtro sucio/obstruido", "Carcasa fisurada"],
    enChequeoRapido: false,
  },
  {
    id: "frenos",
    nombre: "Frenos",
    icono: "freno",
    criticidad: "rojo",
    descripcion: "Sistema que reduce la velocidad del bus y lo detiene por completo.",
    funcion: "Convierte la energía cinética en calor mediante fricción para frenar el vehículo de forma segura.",
    importancia:
      "Es el sistema de seguridad más crítico del bus: una falla de frenos pone en riesgo inmediato la vida de pasajeros, conductor y terceros.",
    pasosInspeccion: [
      "Verificar el nivel del depósito de líquido de frenos (o la presión de aire, según el sistema).",
      "Con el bus detenido, pisar el pedal y comprobar que no se hunda progresivamente ni se sienta esponjoso.",
      "Iniciar marcha a baja velocidad y frenar suavemente: el bus debe detenerse en línea recta, sin tirar hacia un lado ni vibrar.",
      "Escuchar si hay chillidos o roce metálico al frenar.",
    ],
    senalesDesgaste: [
      "Pedal esponjoso o que se hunde hasta el piso.",
      "El bus se va hacia un lado al frenar.",
      "Chillido agudo o roce metálico (posible pastilla/banda al límite).",
      "Testigo de freno o de presión de aire encendido.",
    ],
    fallasComunes: ["Bandas o pastillas desgastadas.", "Fuga de líquido de frenos o de aire.", "Discos o tambores rayados."],
    riesgos: ["Pérdida total o parcial de frenado.", "Colisión por distancia de frenado insuficiente.", "Volcamiento por frenado asimétrico."],
    mantenimientoPreventivo: ["Revisión y ajuste periódico de bandas/pastillas y sistema de aire.", "Purga y cambio de líquido de frenos según el fabricante."],
    frecuencia: "Verificación funcional obligatoria antes de cada salida (preoperacional diaria).",
    citasLegales: null,
    buenaPractica:
      "Prueba funcional diaria de frenado a baja velocidad, estándar de seguridad vehicular previo a cualquier salida con pasajeros.",
    tiposNovedad: ["Pedal esponjoso", "Se va hacia un lado", "Chillido o roce", "Testigo encendido", "Fuga de líquido/aire"],
    enChequeoRapido: true,
  },
  {
    id: "suspension",
    nombre: "Suspensión",
    icono: "suspension",
    criticidad: "rojo",
    descripcion: "Conjunto de resortes, amortiguadores y bujes que absorben las irregularidades de la vía.",
    funcion: "Mantiene el contacto de las llantas con el pavimento y estabiliza el bus en curvas y frenadas.",
    importancia: "Una suspensión en mal estado compromete la estabilidad y el control direccional del bus.",
    pasosInspeccion: [
      "Inspeccionar visualmente resortes, fuelles de aire y amortiguadores buscando fugas o deformación.",
      "Empujar cada esquina del bus hacia abajo y soltar: debe volver a su posición sin rebotar más de una vez.",
      "Revisar bujes y bases de amortiguador en busca de holgura o ruido.",
    ],
    senalesDesgaste: ["Rebote excesivo tras un bache.", "Fuga de aceite en el amortiguador.", "Bus inclinado hacia un lado en reposo."],
    fallasComunes: ["Amortiguador descargado.", "Fuelle de aire perforado.", "Bujes desgastados."],
    riesgos: ["Pérdida de control en curvas o frenadas bruscas.", "Desgaste irregular acelerado de llantas."],
    mantenimientoPreventivo: ["Inspección periódica de fuelles, amortiguadores y bujes en el mantenimiento programado."],
    frecuencia: "Inspección visual diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Inspección visual y prueba de rebote estándar antes de cada salida.",
    tiposNovedad: ["Rebote excesivo", "Fuga en amortiguador", "Bus inclinado", "Ruido en suspensión"],
    enChequeoRapido: false,
  },
  {
    id: "direccion",
    nombre: "Dirección",
    icono: "direccion",
    criticidad: "rojo",
    descripcion: "Sistema que permite al conductor controlar la trayectoria del bus.",
    funcion: "Transmite el giro del volante a las ruedas delanteras de forma precisa y proporcional.",
    importancia: "Una falla de dirección elimina la capacidad de maniobrar y evitar un obstáculo o colisión.",
    pasosInspeccion: [
      "Con el motor encendido, girar el volante levemente a ambos lados y sentir si hay juego excesivo antes de que las ruedas respondan.",
      "Verificar el nivel del depósito de dirección hidráulica si aplica.",
      "Durante el arranque, confirmar que el bus responde en línea recta sin tirar hacia un costado.",
    ],
    senalesDesgaste: ["Juego excesivo en el volante.", "Dureza o ruido al girar.", "El bus tira hacia un lado en línea recta."],
    fallasComunes: ["Fuga en la bomba o mangueras de dirección hidráulica.", "Rótulas o terminales desgastados."],
    riesgos: ["Pérdida de control direccional.", "Colisión por incapacidad de maniobrar a tiempo."],
    mantenimientoPreventivo: ["Revisión de rótulas, terminales y nivel de líquido en cada mantenimiento programado."],
    frecuencia: "Verificación funcional diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Prueba funcional diaria de holgura y respuesta del volante, estándar de seguridad vehicular.",
    tiposNovedad: ["Juego excesivo", "Dureza al girar", "Se va hacia un lado", "Ruido al girar"],
    enChequeoRapido: true,
  },
  {
    id: "llantas",
    nombre: "Llantas",
    icono: "llanta",
    criticidad: "rojo",
    descripcion: "Neumáticos que sostienen el peso del bus y transmiten tracción y frenado al pavimento.",
    funcion: "Único punto de contacto entre el bus y la vía: de ellas depende la tracción, el frenado y la estabilidad.",
    importancia: "Una llanta en mal estado puede reventarse en vía a alta velocidad con consecuencias graves.",
    pasosInspeccion: [
      "Revisar la presión de cada llanta (incluida la de repuesto) con manómetro, en frío.",
      "Medir o inspeccionar visualmente la profundidad del labrado en varios puntos de la banda de rodadura.",
      "Buscar cortes, protuberancias (hernias), desgaste irregular u objetos incrustados.",
      "Verificar el ajuste de las tuercas y el estado de los rines.",
    ],
    senalesDesgaste: [
      "Labrado por debajo del mínimo legal (indicadores de desgaste visibles).",
      "Protuberancias o deformaciones en el costado.",
      "Desgaste irregular (indica problema de alineación o presión).",
    ],
    fallasComunes: ["Presión baja o desigual entre ejes.", "Corte profundo por objeto en la vía.", "Tuerca floja."],
    riesgos: ["Reventón en vía a alta velocidad.", "Pérdida de tracción o de control en curva.", "Desprendimiento de rin por tuercas flojas."],
    mantenimientoPreventivo: ["Rotación periódica según el fabricante.", "Alineación y balanceo cuando haya desgaste irregular.", "Reemplazo antes de alcanzar el límite legal de labrado."],
    frecuencia: "Verificación de presión y estado diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Inspección diaria de presión, labrado y daños visibles, estándar de seguridad vehicular.",
    tiposNovedad: ["Presión baja", "Corte o hernia", "Desgaste irregular", "Tuerca floja", "Objeto incrustado"],
    enChequeoRapido: true,
  },
  {
    id: "sistema-electrico",
    nombre: "Sistema eléctrico",
    icono: "electrico",
    criticidad: "rojo",
    descripcion: "Red de cables, fusibles y relés que distribuye energía a todos los sistemas del bus.",
    funcion: "Alimenta luces, tablero, tacógrafo, puertas eléctricas y demás sistemas dependientes de electricidad.",
    importancia: "Una falla eléctrica puede dejar sin luces o sin apertura de puertas en plena vía u ocasionar un corto/incendio.",
    pasosInspeccion: [
      "Encender el switch y verificar que el tablero encienda sin testigos de falla inesperados.",
      "Revisar visualmente que no haya cables sueltos, pelados o quemados a la vista.",
      "Probar los sistemas eléctricos auxiliares (bocina, plumillas, luces interiores).",
    ],
    senalesDesgaste: ["Olor a quemado o cable visiblemente derretido.", "Fusibles que se funden repetidamente.", "Luces que parpadean sin razón aparente."],
    fallasComunes: ["Fusible fundido.", "Conexión a tierra floja u oxidada.", "Cableado rozado por vibración."],
    riesgos: ["Incendio por corto circuito.", "Pérdida simultánea de luces, puertas o tacógrafo en plena vía."],
    mantenimientoPreventivo: ["Revisión de conexiones y estado del cableado en cada mantenimiento programado."],
    frecuencia: "Verificación funcional diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Verificación diaria del tablero y ausencia de cableado expuesto, estándar de seguridad eléctrica vehicular.",
    tiposNovedad: ["Olor a quemado", "Cable expuesto/pelado", "Fusible fundido", "Falla intermitente"],
    enChequeoRapido: true,
  },
  {
    id: "bateria",
    nombre: "Batería",
    icono: "bateria",
    criticidad: "amarillo",
    descripcion: "Acumulador eléctrico que arranca el motor y respalda el sistema eléctrico.",
    funcion: "Suministra la corriente inicial de arranque y estabiliza el voltaje del sistema eléctrico.",
    importancia: "Una batería descargada o en mal estado impide el arranque, dejando el bus fuera de servicio antes de salir a ruta.",
    pasosInspeccion: [
      "Verificar que los bornes estén limpios, ajustados y sin sulfatación (polvo blanco/verdoso).",
      "Revisar que la carcasa no esté hinchada ni presente fugas de electrolito.",
      "Confirmar que el arranque sea firme, sin sonido débil o intermitente.",
    ],
    senalesDesgaste: ["Arranque lento o débil.", "Bornes sulfatados o flojos.", "Carcasa hinchada."],
    fallasComunes: ["Sulfatación de bornes.", "Batería descargada por sistema que quedó encendido.", "Vida útil vencida."],
    riesgos: ["Bus fuera de servicio por no poder arrancar.", "Corrosión por fuga de electrolito."],
    mantenimientoPreventivo: ["Limpieza de bornes y verificación de carga en cada mantenimiento programado."],
    frecuencia: "Verificación visual diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Inspección diaria de bornes y firmeza de arranque, estándar de mantenimiento automotor.",
    tiposNovedad: ["Arranque débil", "Bornes sulfatados", "Carcasa hinchada/fuga"],
    enChequeoRapido: false,
  },
  {
    id: "alternador",
    nombre: "Alternador",
    icono: "alternador",
    criticidad: "amarillo",
    descripcion: "Generador que recarga la batería y alimenta el sistema eléctrico con el motor en marcha.",
    funcion: "Convierte energía mecánica del motor en energía eléctrica para sostener todos los consumos del bus en marcha.",
    importancia: "Si falla, el bus consume solo de la batería y se queda sin energía (luces, tacógrafo) en pocos minutos de ruta.",
    pasosInspeccion: [
      "Con el motor en marcha, verificar que el testigo de carga del tablero permanezca apagado.",
      "Revisar tensión y estado de la correa del alternador.",
      "Escuchar ruidos de rodamiento (chillido agudo) provenientes del alternador.",
    ],
    senalesDesgaste: ["Testigo de carga encendido con el motor en marcha.", "Correa floja, agrietada o que chilla.", "Luces que se atenúan en ralentí."],
    fallasComunes: ["Correa desgastada o desalineada.", "Escobillas o rodamiento interno gastado."],
    riesgos: ["Descarga progresiva de la batería y apagado del bus en ruta.", "Pérdida de luces o tacógrafo en marcha."],
    mantenimientoPreventivo: ["Revisión de tensión y estado de correa en cada mantenimiento programado."],
    frecuencia: "Verificación visual/funcional diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Verificación diaria del testigo de carga y la correa, estándar de mantenimiento automotor.",
    tiposNovedad: ["Testigo de carga encendido", "Correa floja o chillona", "Luces se atenúan"],
    enChequeoRapido: false,
  },
  {
    id: "luces",
    nombre: "Luces",
    icono: "luz",
    criticidad: "rojo",
    descripcion: "Conjunto de faros, direccionales, luces de freno, posición y reversa del bus.",
    funcion: "Hacen visible el bus y comunican sus maniobras a otros actores de la vía, de día y de noche.",
    importancia: "Sin luces funcionando el bus es invisible o impredecible para otros conductores, sobre todo de noche o en frenadas.",
    pasosInspeccion: [
      "Con ayuda de otra persona (o pared/vidrio reflejante), probar una a una: altas, bajas, direccionales, freno, posición, placa y reversa.",
      "Verificar que ninguna esté fundida, opaca por humedad o con el lente roto.",
      "Confirmar que la intensidad sea uniforme entre el lado izquierdo y el derecho.",
    ],
    senalesDesgaste: ["Luz fundida o intermitente.", "Lente opaco, agrietado o con humedad interna.", "Intensidad baja o parpadeo."],
    fallasComunes: ["Bombillo fundido.", "Fusible o relé de la luz averiado.", "Conector oxidado."],
    riesgos: ["Colisión por no ser visible en la vía.", "Sanción por circular sin equipo de luces completo."],
    mantenimientoPreventivo: ["Reemplazo inmediato de cualquier luz fundida antes de salir a ruta."],
    frecuencia: "Verificación funcional diaria (preoperacional), cada una de las luces.",
    citasLegales: null,
    buenaPractica: "Prueba funcional diaria de cada luz, estándar de seguridad vehicular previo a cualquier salida.",
    tiposNovedad: ["No enciende", "Intensidad baja/parpadeo", "Lente roto u opaco"],
    enChequeoRapido: true,
  },
  {
    id: "limpiabrisas",
    nombre: "Limpiabrisas",
    icono: "limpiaparabrisas",
    criticidad: "rojo",
    descripcion: "Sistema de plumillas y motor que limpia el parabrisas de agua, polvo y suciedad.",
    funcion: "Mantiene la visibilidad del conductor a través del parabrisas en lluvia o suciedad.",
    importancia: "Sin visibilidad clara del parabrisas el conductor no puede reaccionar a tiempo ante un obstáculo o peatón.",
    pasosInspeccion: [
      "Accionar el limpiabrisas en cada velocidad y verificar que barra todo el parabrisas sin dejar franjas.",
      "Revisar el estado de goma de las plumillas (agrietada o endurecida).",
      "Verificar el nivel del depósito de líquido limpiaparabrisas y que el aspersor funcione.",
    ],
    senalesDesgaste: ["Franjas o zonas sin limpiar.", "Ruido de raspado (metal contra vidrio).", "Goma agrietada o levantada."],
    fallasComunes: ["Plumilla reseca por sol.", "Motor de limpiabrisas débil o trabado.", "Aspersor obstruido."],
    riesgos: ["Pérdida de visibilidad en lluvia.", "Colisión por no ver a tiempo un obstáculo."],
    mantenimientoPreventivo: ["Reemplazo periódico de plumillas.", "Rellenar el depósito de líquido limpiaparabrisas."],
    frecuencia: "Verificación funcional diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Prueba funcional diaria del barrido y del líquido, estándar de seguridad vehicular.",
    tiposNovedad: ["No barre bien / deja franjas", "Ruido de raspado", "Sin líquido"],
    enChequeoRapido: true,
  },
  {
    id: "espejos",
    nombre: "Espejos",
    icono: "espejo",
    criticidad: "amarillo",
    descripcion: "Espejos retrovisores exteriores e interiores del bus.",
    funcion: "Dan visibilidad de los costados y la parte trasera, zonas ciegas para el conductor.",
    importancia: "Sin espejos en buen estado el conductor pierde visión de peatones, ciclistas y vehículos en el punto ciego.",
    pasosInspeccion: [
      "Revisar que estén firmes en su soporte, sin holgura ni vibración.",
      "Verificar que el vidrio no esté roto, opaco o desprendido.",
      "Ajustar el ángulo desde el puesto del conductor y confirmar cobertura de ambos costados.",
    ],
    senalesDesgaste: ["Vidrio agrietado, opaco o con manchas de humedad.", "Soporte flojo que vibra en marcha."],
    fallasComunes: ["Rotura por impacto.", "Soporte o articulación desajustada."],
    riesgos: ["Punto ciego ampliado.", "Colisión al cambiar de carril o girar."],
    mantenimientoPreventivo: ["Ajuste y reemplazo de vidrio cuando esté dañado, antes de salir a ruta."],
    frecuencia: "Verificación visual diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Verificación diaria de firmeza y estado del vidrio, estándar de seguridad vehicular.",
    tiposNovedad: ["Vidrio roto/opaco", "Soporte flojo"],
    enChequeoRapido: false,
  },
  {
    id: "puertas",
    nombre: "Puertas",
    icono: "puerta",
    criticidad: "rojo",
    descripcion: "Puertas de acceso y salida de pasajeros, manuales o de accionamiento neumático/eléctrico.",
    funcion: "Permiten el ascenso y descenso seguro de los pasajeros y se cierran de forma hermética en marcha.",
    importancia: "Una puerta que no cierra bien o se abre en marcha es un riesgo directo de caída de un pasajero.",
    pasosInspeccion: [
      "Abrir y cerrar cada puerta varias veces verificando que selle completamente y sin trabarse.",
      "Revisar el mecanismo de emergencia de apertura manual.",
      "Verificar que no haya bordes filosos, tornillos sueltos o vidrios rotos en el marco.",
    ],
    senalesDesgaste: ["No cierra completamente o queda floja.", "Ruido o esfuerzo excesivo al operar.", "Fuga de aire audible en la puerta neumática."],
    fallasComunes: ["Sello de goma desgastado.", "Falla del actuador neumático/eléctrico.", "Bisagra o riel desalineado."],
    riesgos: ["Caída de un pasajero por apertura en marcha.", "Ingreso de agua o ruido por sello deteriorado."],
    mantenimientoPreventivo: ["Lubricación de rieles y bisagras, ajuste del sello en cada mantenimiento programado."],
    frecuencia: "Verificación funcional diaria (preoperacional), cada puerta.",
    citasLegales: null,
    buenaPractica: "Prueba funcional diaria de cierre y sello, estándar de seguridad vehicular para transporte de pasajeros.",
    tiposNovedad: ["No cierra bien", "Se traba", "Fuga de aire", "Mecanismo de emergencia dañado"],
    enChequeoRapido: true,
  },
  {
    id: "ventanas",
    nombre: "Ventanas",
    icono: "ventana",
    criticidad: "amarillo",
    descripcion: "Ventanas fijas y corredizas de la cabina de pasajeros.",
    funcion: "Proveen ventilación e iluminación natural, y algunas actúan como salida de emergencia adicional.",
    importancia: "Un vidrio roto o un mecanismo trabado reduce la ventilación y puede impedir una salida de emergencia.",
    pasosInspeccion: [
      "Revisar que ningún vidrio esté roto, rajado o suelto de su marco.",
      "Verificar que las ventanas corredizas abran y cierren sin trabarse.",
      "Confirmar que los seguros o mecanismos de ventana-salida de emergencia funcionen.",
    ],
    senalesDesgaste: ["Vidrio rajado o con impacto.", "Mecanismo de corredera trabado u oxidado.", "Empaque de goma deteriorado."],
    fallasComunes: ["Riel sucio u oxidado.", "Vidrio flojo en el marco."],
    riesgos: ["Vidrio que se desprende en marcha.", "Ventana de emergencia inoperante en caso de accidente."],
    mantenimientoPreventivo: ["Limpieza y lubricación de rieles, ajuste de empaques."],
    frecuencia: "Verificación visual diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Inspección diaria de vidrios y mecanismos, estándar de mantenimiento de carrocería.",
    tiposNovedad: ["Vidrio roto/rajado", "No abre o cierra", "Empaque deteriorado"],
    enChequeoRapido: false,
  },
  {
    id: "cinturones",
    nombre: "Cinturones de seguridad",
    icono: "cinturon",
    criticidad: "rojo",
    descripcion: "Sistema de retención del conductor y, cuando el bus los tiene instalados, de los pasajeros.",
    funcion: "Retiene al ocupante en su puesto ante una frenada brusca o colisión, reduciendo el riesgo de lesión.",
    importancia: "Su uso es obligatorio para el conductor y, cuando existen, también para los pasajeros (Código Nacional de Tránsito).",
    pasosInspeccion: [
      "Extender completamente cada cinturón y verificar que la cinta no esté cortada, deshilachada ni quemada.",
      "Comprobar que la hebilla cierra firme y libera al presionar el botón.",
      "Verificar que el retractor recoja la cinta sin trabarse.",
    ],
    senalesDesgaste: ["Cinta deshilachada, cortada o decolorada por sol.", "Hebilla que no cierra o no libera.", "Retractor que no recoge la cinta."],
    fallasComunes: ["Mecanismo de retracción trabado por suciedad.", "Hebilla desgastada."],
    riesgos: ["Lesión grave o eyección del ocupante en una colisión o frenada brusca."],
    mantenimientoPreventivo: ["Reemplazo inmediato de cualquier cinturón dañado, nunca reparar la cinta."],
    frecuencia: "Verificación visual diaria (preoperacional), del puesto del conductor como mínimo.",
    citasLegales: null,
    buenaPractica:
      "Verificación diaria de estado y funcionamiento; el uso del cinturón es obligatorio para el conductor y pasajeros según el Código Nacional de Tránsito.",
    tiposNovedad: ["Cinta dañada", "Hebilla no cierra/libera", "Retractor no recoge"],
    enChequeoRapido: true,
  },
  {
    id: "salidas-martillos-emergencia",
    nombre: "Salidas y martillos de emergencia",
    icono: "salida-emergencia",
    criticidad: "rojo",
    descripcion: "Ventanas o techos designados como salida de emergencia y los martillos rompevidrios asociados.",
    funcion: "Permiten la evacuación rápida de pasajeros cuando la puerta principal no es utilizable (accidente, incendio, volcamiento).",
    importancia: "En una emergencia real, la falta de un martillo o una salida trabada puede costar vidas por imposibilidad de evacuar.",
    pasosInspeccion: [
      "Verificar que cada martillo esté en su soporte, accesible y sin el vidrio de protección roto (si aplica).",
      "Comprobar que el mecanismo de apertura de cada salida de emergencia no esté obstruido ni trabado.",
      "Revisar que la señalización de salida de emergencia sea visible.",
    ],
    senalesDesgaste: ["Martillo ausente o suelto del soporte.", "Mecanismo de salida oxidado o trabado.", "Señalización desgastada o ilegible."],
    fallasComunes: ["Martillo retirado y no reemplazado.", "Salida bloqueada por equipaje u objetos."],
    riesgos: ["Imposibilidad de evacuar a tiempo en una emergencia.", "Sanción por no portar el equipo mínimo de seguridad."],
    mantenimientoPreventivo: ["Reposición inmediata de cualquier martillo faltante y despeje de las salidas de emergencia."],
    frecuencia: "Verificación diaria (preoperacional): equipo de carretera y de emergencia.",
    citasLegales: CITAS_EQUIPO_CARRETERA,
    tiposNovedad: ["Martillo faltante", "Salida obstruida/trabada", "Señalización dañada"],
    enChequeoRapido: true,
  },
  {
    id: "botiquin",
    nombre: "Botiquín de primeros auxilios",
    icono: "botiquin",
    criticidad: "amarillo",
    descripcion: "Equipo con insumos básicos para atender una lesión menor mientras llega ayuda profesional.",
    funcion: "Permite una primera atención a un pasajero o al conductor ante un incidente menor durante el recorrido.",
    importancia: "Es equipo obligatorio de carretera; su ausencia o insumos vencidos dejan sin respuesta una emergencia menor.",
    pasosInspeccion: [
      "Verificar que el botiquín esté presente, accesible y con el candado o cierre en buen estado.",
      "Revisar el listado de insumos contra el contenido real (ver módulo Primeros auxilios).",
      "Verificar fechas de vencimiento de gasas, antisépticos y demás insumos.",
    ],
    senalesDesgaste: ["Insumos vencidos.", "Faltantes respecto al listado mínimo.", "Empaque húmedo o deteriorado."],
    fallasComunes: ["Insumos usados y no repuestos.", "Botiquín descargado del bus por error."],
    riesgos: ["Sin atención de primeros auxilios ante una emergencia menor.", "Sanción por no portar el equipo obligatorio."],
    mantenimientoPreventivo: ["Reposición de insumos usados o vencidos tras cada inspección o incidente."],
    frecuencia: "Verificación diaria (preoperacional).",
    citasLegales: CITAS_EQUIPO_CARRETERA,
    tiposNovedad: ["Insumo vencido", "Faltante", "Botiquín ausente"],
    enChequeoRapido: true,
  },
  {
    id: "extintor",
    nombre: "Extintor",
    icono: "extintor",
    criticidad: "rojo",
    descripcion: "Equipo portátil para combatir un conato de incendio a bordo.",
    funcion: "Permite sofocar un fuego incipiente antes de que se propague al bus.",
    importancia: "Es equipo obligatorio de carretera; un extintor descargado o vencido deja al bus sin respuesta ante un incendio.",
    pasosInspeccion: [
      "Verificar que el manómetro marque en la zona verde (cargado).",
      "Revisar la fecha de vencimiento o de la última recarga en la etiqueta.",
      "Comprobar que el precinto de seguridad esté intacto y el soporte firme.",
    ],
    senalesDesgaste: ["Manómetro en zona roja (descargado).", "Vencido según etiqueta.", "Precinto roto o carcasa corroída."],
    fallasComunes: ["Descarga parcial no detectada.", "Vencimiento de la recarga."],
    riesgos: ["Sin respuesta ante un incendio a bordo.", "Sanción por no portar el equipo obligatorio en buen estado."],
    mantenimientoPreventivo: ["Recarga o reemplazo según la fecha de vencimiento del proveedor certificado."],
    frecuencia: "Verificación diaria (preoperacional).",
    citasLegales: CITAS_EQUIPO_CARRETERA,
    tiposNovedad: ["Descargado", "Vencido", "Extintor ausente", "Soporte flojo"],
    enChequeoRapido: true,
  },
  {
    id: "senales-triangulos",
    nombre: "Señales / triángulos",
    icono: "triangulo",
    criticidad: "amarillo",
    descripcion: "Señales reflectivas de carretera (triángulos) o lámparas intermitentes para advertir una emergencia en vía.",
    funcion: "Advierten a otros conductores la presencia del bus detenido en la vía por una falla o emergencia.",
    importancia: "Son equipo obligatorio de carretera; sin ellas un bus varado es un riesgo de colisión por alcance para los demás vehículos.",
    pasosInspeccion: [
      "Verificar que estén presentes las dos señales exigidas.",
      "Revisar que el material reflectivo no esté opaco, roto o incompleto.",
      "Comprobar que los soportes permitan colocarlas en posición vertical.",
    ],
    senalesDesgaste: ["Reflectivo opaco o descolorido.", "Soporte roto o faltante.", "Solo una señal presente en vez de dos."],
    fallasComunes: ["Pérdida o préstamo no devuelto.", "Deterioro del material reflectivo por sol."],
    riesgos: ["Colisión por alcance a un bus varado sin señalización visible.", "Sanción por no portar el equipo obligatorio."],
    mantenimientoPreventivo: ["Reposición inmediata de cualquier señal faltante o deteriorada."],
    frecuencia: "Verificación diaria (preoperacional).",
    citasLegales: CITAS_EQUIPO_CARRETERA,
    tiposNovedad: ["Señal faltante", "Reflectivo deteriorado", "Soporte roto"],
    enChequeoRapido: false,
  },
  {
    id: "herramientas-gato",
    nombre: "Herramientas y gato",
    icono: "herramientas",
    criticidad: "verde",
    descripcion: "Gato hidráulico o mecánico, cruceta, tacos de bloqueo y caja de herramienta básica.",
    funcion: "Permiten realizar un cambio de llanta u otra intervención menor de emergencia en vía.",
    importancia: "Son equipo obligatorio de carretera; sin ellos, una llanta averiada inmoviliza el bus hasta que llegue ayuda externa.",
    pasosInspeccion: [
      "Verificar la presencia del gato con capacidad suficiente para el bus y de la cruceta.",
      "Comprobar que los dos tacos de bloqueo estén presentes.",
      "Revisar la caja de herramienta básica: alicate, destornilladores, llave de expansión y llaves fijas.",
    ],
    senalesDesgaste: ["Gato que no sostiene presión o con fuga hidráulica.", "Herramienta faltante del set básico.", "Tacos ausentes o deteriorados."],
    fallasComunes: ["Préstamo de una herramienta no devuelto.", "Gato con fuga de aceite hidráulico."],
    riesgos: ["Imposibilidad de cambiar una llanta averiada en vía.", "Sanción por no portar el equipo obligatorio."],
    mantenimientoPreventivo: ["Reposición inmediata de cualquier herramienta faltante o dañada."],
    frecuencia: "Verificación diaria (preoperacional).",
    citasLegales: CITAS_EQUIPO_CARRETERA,
    tiposNovedad: ["Herramienta faltante", "Gato no sostiene presión", "Taco faltante"],
    enChequeoRapido: false,
  },
  {
    id: "tacografo",
    nombre: "Tacógrafo",
    icono: "tacografo",
    criticidad: "verde",
    descripcion: "Dispositivo que registra velocidad, tiempo de conducción y descanso del conductor.",
    funcion: "Documenta el comportamiento de conducción para control de la empresa y de la autoridad de tránsito.",
    importancia: "Un tacógrafo dañado o sin registro impide demostrar cumplimiento de tiempos de conducción y descanso.",
    pasosInspeccion: [
      "Verificar que el equipo encienda y muestre hora y fecha correctas.",
      "Confirmar que no haya mensajes de error en pantalla.",
      "Revisar que el sello o precinto de calibración esté intacto (si aplica).",
    ],
    senalesDesgaste: ["No enciende o pantalla en blanco.", "Mensaje de error persistente.", "Sello de calibración roto."],
    fallasComunes: ["Falla de alimentación eléctrica del equipo.", "Vencimiento de calibración."],
    riesgos: ["Imposibilidad de acreditar tiempos de conducción ante un control.", "Sanción administrativa."],
    mantenimientoPreventivo: ["Calibración periódica según el proveedor y revisión de la conexión eléctrica."],
    frecuencia: "Verificación funcional diaria (preoperacional).",
    citasLegales: null,
    buenaPractica: "Verificación diaria de encendido y ausencia de errores, estándar operativo de transporte de pasajeros.",
    tiposNovedad: ["No enciende", "Mensaje de error", "Sello roto"],
    enChequeoRapido: false,
  },
];

export function obtenerComponente(id: string): ComponenteBus | undefined {
  return componentes.find((c) => c.id === id);
}

export function componentesDeChequeoRapido(): ComponenteBus[] {
  return componentes.filter((c) => c.enChequeoRapido);
}

/** ids válidos, usado por zod para validar componente_id en las Server Actions. */
export const idsComponentes = componentes.map((c) => c.id) as [string, ...string[]];
